version: '3'
services:
    upload:
        build: .
        environment:
          - URL=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
          - FILENAME=awscli-exe-linux-x86_64.zip
          - BUCKET=test